baseURL = "https://alexey.is/"
title = "Alexey Gornostaev"
languageCode = "en-us"
theme = "accujazz"
summaryLength = 7
paginate = 5
rssLimit = 10

[params]
  author = "Alexey Gornostaev"
  description = "Alexey Gornostaev's personal website."

[permalinks]
	post = "/:year/:month/:title/"	